/**
 * B-7 (P0) destination-tier acceptance suite: the migrated `places` spine
 * carries the bootstrap Overture `divisions`/`division`/`locality` seed
 * (migration `drizzle/0004_destination_tier_seed.sql`, generated by
 * `scripts/generate-destination-tier.ts` from
 * `reference-data/destinations.json`) — proving the actual B-7 fix, not
 * just the pipeline that produced it (`region-ingest.db.test.ts` /
 * `routes.db.test.ts` already cover ingest/search mechanics generally).
 *
 * The B-7 repro (below) exercises `GET /places/search?q=<city>` with NO
 * bbox/near — the exact request shape the destination picker sends
 * (`apps/mobile/src/data/trips-mutations.ts`, options brief §1 step 2):
 * before this migration, this was categorically unreachable-by-data on a
 * fresh install (0 rows in `places`, ever, per `fresh-install.db.test.ts`'s
 * evidence pin). It is reachable now because the row EXISTS before any
 * search ever runs, not because search behavior changed.
 *
 * Driver: postgres-js on ephemeral testcontainers Postgres, shared-template
 * pattern (T-S3.3) — a Docker-less CI run is a HARD FAILURE; local skips
 * with a loud banner. No network beyond the local container (Law #5).
 */
import { eq } from "drizzle-orm";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { createLocalJWKSet, generateKeyPair } from "jose";
import { afterAll, beforeAll, describe, expect, inject, it } from "vitest";
import { paginatedSchema } from "@gogo/shared/api/envelope";
import { PlaceSchema } from "@gogo/shared/domains/place";
import { createApp } from "../app.js";
import { createUserWithEntitlements } from "../db/create-user.js";
import * as schema from "../db/schema/index.js";
import { createSessionWithTokens, type AccessTokenSigner } from "../auth/token-issuer.js";
import type { AuthRouterDeps } from "../auth/routes.js";
import type { ErrorEnvelope } from "../http/idor-404.test-util.js";
import { createSuiteDb, type SuiteDb } from "../test/suite-db.js";

const dockerAvailable = inject("dbAvailable");

const BOOT_TIMEOUT_MS = 240_000;
const SIGNER_KID = "gogo-es256-2026-09-destination-tier";

const PaginatedPlacesSchema = paginatedSchema(PlaceSchema);

/**
 * Pins straight from the committed `reference-data/destinations.json`
 * snapshot (2026-08-19.0 release) — re-run `generate-destination-tier.ts`
 * and diff before changing any of these. Not guessed: every value here is
 * copied from the actual generated file.
 */
const TOKYO = {
  sourceId: "798895d4-5005-4b1d-b805-ee44a1f99a54",
  name: "Tokyo",
  lat: 35.676856994628906,
  lng: 139.76388549804688,
};
const ATHENS_GR = {
  sourceId: "adfbf49a-2781-4b77-8f02-b8ba400d50c6",
  name: "Athens",
  lat: 37.975563049316406,
  lng: 23.73482894897461,
};
const ATHENS_US = {
  sourceId: "3f0b8068-757c-4a76-9581-1c7201ff4254",
  name: "Athens",
  lat: 33.95976638793945,
  lng: -83.37641143798828,
};
const REYKJAVIK = {
  sourceId: "bc4247c1-deba-438e-bb36-788fec678333",
  name: "Reykjavik",
  lat: 64.14598083496094,
  lng: -21.94223976135254,
};
const ROME = { sourceId: "6fe9e7a3-65c4-4a9c-9aa2-3dddad62e1ab", name: "Rome" };
const OSLO = { sourceId: "2c1524a7-8d54-480e-b335-11a7d7918942", name: "Oslo" };
/** Netherlands — leading apostrophe (`'s-Hertogenbosch`). */
const APOSTROPHE_NAME = {
  sourceId: "b937075e-cb36-4d3e-a39e-97eac1dcba3f",
  name: "'s-Hertogenbosch",
};
/** Brazil — NFC diacritic, and the same name normalize.ts's own doc-comment
 * uses as its canonical example ("Belém" NFD vs NFC). */
const DIACRITIC_NAME = { sourceId: "bf9c8e9b-9b65-4044-9417-1d28f3dce674", name: "Belém" };
/** Iran — RTL script, embedded parentheses. */
const RTL_NAME = {
  sourceId: "300b9717-8013-46bf-a787-87be948fdd43",
  name: "(شهرک ابراهیم (شهید آیت الله ابراهیم رئیسی",
};
/** China — CJK, exactly 4 chars (clears PLACES_SEARCH_TEXT_ONLY_MIN_CHARS). */
const CJK_NAME = { sourceId: "8c239f23-c0e7-4ea0-8f11-f0f8317baf3e", name: "千泉街道" };

describe.skipIf(!dockerAvailable)("B-7 bootstrap destination tier (migrated seed)", () => {
  let suiteDb: SuiteDb;
  let db: PostgresJsDatabase<typeof schema>;
  let app: ReturnType<typeof createApp>;
  let signer: AccessTokenSigner;

  let seq = 0;
  const uniq = () => `${Date.now().toString(36)}${(seq++).toString(36)}`;

  beforeAll(async () => {
    suiteDb = await createSuiteDb("destination_tier");
    db = suiteDb.db;

    const signerPair = await generateKeyPair("ES256");
    signer = { privateKey: signerPair.privateKey, kid: SIGNER_KID };
    const authDeps: AuthRouterDeps = {
      db,
      verifier: {
        appleJwks: createLocalJWKSet({ keys: [] }),
        googleJwks: createLocalJWKSet({ keys: [] }),
        appleAudience: "com.gogo.travel",
        googleAudiences: ["gid.apps.example"],
      },
      signer,
      accessVerify: { publicKey: signerPair.publicKey },
      appleExchange: { exchange: () => Promise.reject(new Error("unused in this suite")) },
      appleCredentialsKey: Buffer.alloc(32, 7),
      logger: { warn: () => undefined },
    };
    app = createApp({
      auth: authDeps,
      places: {
        db,
        placesIngest: { enqueueDestination: () => undefined, enqueueSearchMiss: () => undefined },
        trackCoverageTask: (task) => {
          void task;
        },
      },
    });
  }, BOOT_TIMEOUT_MS);

  afterAll(async () => {
    await suiteDb?.drop();
  });

  async function seedUserWithToken() {
    const { user } = await createUserWithEntitlements(db, {
      email: `destination-tier-${uniq()}@example.com`,
      displayName: "Destination Tester",
      googleSub: `google-${uniq()}`,
    });
    const issued = await createSessionWithTokens(db, {
      userId: user.id,
      device: { platform: "ios" },
      signer,
    });
    return { userId: user.id, accessToken: issued.accessToken };
  }

  const request = (path: string, token?: string, init?: RequestInit) =>
    app.request(path, {
      ...init,
      headers: {
        ...(init?.body ? { "content-type": "application/json" } : {}),
        ...(token ? { authorization: `Bearer ${token}` } : {}),
        ...(init?.headers ?? {}),
      },
    });

  const search = (token: string | undefined, query: string) =>
    request(`/api/places/search?${query}`, token);

  async function searchOk(token: string, query: string) {
    const res = await search(token, query);
    expect(res.status).toBe(200);
    return PaginatedPlacesSchema.parse(await res.json());
  }

  // ===========================================================================
  // Row count pin (migration 0004)
  // ===========================================================================

  it("migration 0004 seeded exactly 6,927 overture/locality rows", async () => {
    const [row] = await suiteDb.client<
      { n: string }[]
    >`select count(*) as n from places where source = 'overture' and category = 'locality'`;
    expect(Number(row?.n)).toBe(6927);
  });

  // ===========================================================================
  // [B-7 repro] text-only destination search finds the bootstrap tier
  // ===========================================================================

  it("[B-7 repro] a text-only destination search (no bbox/near — the picker's exact request shape) finds Athens, Tokyo, and Reykjavik", async () => {
    const user = await seedUserWithToken();
    for (const city of [TOKYO, REYKJAVIK] as const) {
      const page = await searchOk(user.accessToken, `q=${encodeURIComponent(city.name)}`);
      expect(page.items.length).toBeGreaterThan(0);
      const hit = page.items.find((p) => p.source_id === city.sourceId);
      expect(hit, `${city.name} (${city.sourceId}) not found in results`).toBeDefined();
      expect(hit?.source).toBe("overture");
      expect(hit?.category).toBe("locality");
      expect(hit?.coarse_category).toBe("other"); // no `locality` rule (documented, README)
    }
    // Athens is ambiguous (GR capital + a US city) — both real tier rows,
    // both must surface (the duplicate-names case, verified below too).
    const athens = await searchOk(user.accessToken, "q=Athens");
    expect(athens.items.some((p) => p.source_id === ATHENS_GR.sourceId)).toBe(true);
    expect(athens.items.some((p) => p.source_id === ATHENS_US.sourceId)).toBe(true);
  });

  it("4-char text-only query (the existing global floor, PLACES_SEARCH_TEXT_ONLY_MIN_CHARS) finds Rome and Oslo", async () => {
    const user = await seedUserWithToken();
    for (const city of [ROME, OSLO] as const) {
      expect(city.name.length).toBe(4);
      const page = await searchOk(user.accessToken, `q=${city.name}`);
      expect(page.items.some((p) => p.source_id === city.sourceId)).toBe(true);
    }
  });

  it("3-char text-only query is rejected — the destination tier does not relax the existing floor", async () => {
    const user = await seedUserWithToken();
    const res = await search(user.accessToken, "q=Rio"); // 3 chars, no geo bound
    expect(res.status).toBe(400);
    expect(((await res.json()) as ErrorEnvelope).error.code).toBe("VALIDATION_FAILED");
  });

  // ===========================================================================
  // Ranking: custom place vs. tier row sharing a name (Law #3 posture)
  // ===========================================================================

  it("ranking: a same-named custom place and the tier row blend by proximity; the custom place stays creator-scoped", async () => {
    const creator = await seedUserWithToken();
    const stranger = await seedUserWithToken();

    // A custom place named exactly "Reykjavik", seeded much closer to the
    // near-anchor than the real tier row (64.146,-21.942) — same trigram
    // similarity to `q=reykjavik` (exact name match either way), so the
    // BLEND's proximity term is what decides the order (search-query.ts's
    // documented "similarity ties -> nearer wins" rule) — genuinely
    // untestable before this migration (there was no same-named spine row).
    const anchor = { lat: 64.1, lng: -21.9 }; // ~5.5km from the real tier row
    const customRes = await request("/api/places", creator.accessToken, {
      method: "POST",
      body: JSON.stringify({ name: "Reykjavik", lat: 64.101, lng: -21.901 }), // ~120m from anchor
    });
    expect(customRes.status).toBe(201);
    const custom = PlaceSchema.parse(await customRes.json());

    const blended = await searchOk(
      creator.accessToken,
      `q=reykjavik&near=${anchor.lat},${anchor.lng}&radius_m=50000`,
    );
    const ids = blended.items.map((p) => p.id);
    expect(ids).toContain(custom.id);
    const customIdx = ids.indexOf(custom.id);
    const tierIdx = blended.items.findIndex((p) => p.source_id === REYKJAVIK.sourceId);
    expect(tierIdx).toBeGreaterThanOrEqual(0);
    expect(customIdx).toBeLessThan(tierIdx); // nearer (custom) ranks first

    // Law #3: the stranger never sees the custom "Reykjavik" — only the
    // real tier row, even though names and query tie exactly.
    const strangerView = await searchOk(
      stranger.accessToken,
      `q=reykjavik&near=${anchor.lat},${anchor.lng}&radius_m=50000`,
    );
    expect(strangerView.items.some((p) => p.id === custom.id)).toBe(false);
    expect(strangerView.items.some((p) => p.source_id === REYKJAVIK.sourceId)).toBe(true);
  });

  // ===========================================================================
  // Duplicate names across countries (real data — no fixture needed)
  // ===========================================================================

  it("duplicate names across countries are both present and distinguishable by id/coordinates", async () => {
    const [gr] = await db
      .select()
      .from(schema.places)
      .where(eq(schema.places.sourceId, ATHENS_GR.sourceId));
    const [us] = await db
      .select()
      .from(schema.places)
      .where(eq(schema.places.sourceId, ATHENS_US.sourceId));
    expect(gr?.name).toBe("Athens");
    expect(us?.name).toBe("Athens");
    expect(gr?.id).not.toBe(us?.id);
    expect(Number(gr?.lat)).toBeCloseTo(ATHENS_GR.lat, 3);
    expect(Number(us?.lat)).toBeCloseTo(ATHENS_US.lat, 3);
    // ~9,600 km apart — genuinely two different places, not a dedup bug.
    expect(Math.abs(Number(gr?.lat) - Number(us?.lat))).toBeGreaterThan(3);
  });

  // ===========================================================================
  // Adversarial names survive the SQL emitter (real rows, not synthesized)
  // ===========================================================================

  it("adversarial names (apostrophe, diacritic, RTL, CJK) round-trip byte-for-byte through the SQL emitter", async () => {
    for (const row of [APOSTROPHE_NAME, DIACRITIC_NAME, RTL_NAME, CJK_NAME]) {
      const [found] = await db
        .select()
        .from(schema.places)
        .where(eq(schema.places.sourceId, row.sourceId));
      expect(found, `${row.sourceId} missing`).toBeDefined();
      expect(found?.name).toBe(row.name);
    }
  });

  it("apostrophe and diacritic names are ALSO findable via the search endpoint (storage AND search both survive)", async () => {
    const user = await seedUserWithToken();
    const hertogenbosch = await searchOk(user.accessToken, "q=Hertogenbosch");
    expect(hertogenbosch.items.some((p) => p.source_id === APOSTROPHE_NAME.sourceId)).toBe(true);

    const belem = await searchOk(user.accessToken, `q=${encodeURIComponent("belém")}`);
    expect(belem.items.some((p) => p.source_id === DIACRITIC_NAME.sourceId)).toBe(true);
  });
});
