/**
 * B-7 (P0) destination-tier acceptance suite: the migrated `places` spine
 * carries the bootstrap Overture `divisions`/`division`/`locality` seed
 * (migration `drizzle/0004_destination_tier_seed.sql`, generated by
 * `scripts/generate-destination-tier.ts` from
 * `reference-data/destinations.json`) — proving the actual B-7 fix, not
 * just the pipeline that produced it (`region-ingest.db.test.ts` /
 * `routes.db.test.ts` already cover ingest/search mechanics generally).
 *
 * The B-7 repro (below) exercises `GET /places/search?q=<city>` with NO
 * bbox/near — the exact request shape the destination picker sends
 * (`apps/mobile/src/data/trips-mutations.ts`, options brief §1 step 2):
 * before this migration, this was categorically unreachable-by-data on a
 * fresh install (0 rows in `places`, ever, per `fresh-install.db.test.ts`'s
 * evidence pin). It is reachable now because the row EXISTS before any
 * search ever runs, not because search behavior changed.
 *
 * Driver: postgres-js on ephemeral testcontainers Postgres, shared-template
 * pattern (T-S3.3) — a Docker-less CI run is a HARD FAILURE; local skips
 * with a loud banner. No network beyond the local container (Law #5).
 */
import { eq } from "drizzle-orm";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { createLocalJWKSet, generateKeyPair } from "jose";
import { afterAll, beforeAll, describe, expect, inject, it } from "vitest";
import { paginatedSchema } from "@gogo/shared/api/envelope";
import { PlaceSchema } from "@gogo/shared/domains/place";
import { TripWithRoleSchema } from "@gogo/shared/domains/trip";
import { createApp } from "../app.js";
import { createUserWithEntitlements } from "../db/create-user.js";
import * as schema from "../db/schema/index.js";
import { createSessionWithTokens, type AccessTokenSigner } from "../auth/token-issuer.js";
import type { AuthRouterDeps } from "../auth/routes.js";
import type { ErrorEnvelope } from "../http/idor-404.test-util.js";
import { placesExactTierMatchQuery, placesSearchQuery } from "./search-query.js";
import { DESTINATION_TIER_ROW_COUNT } from "../test/destination-tier-fixture.js";
import { encodeKeysetCursor } from "../http/keyset-cursor.js";
import { createSuiteDb, type SuiteDb } from "../test/suite-db.js";

const dockerAvailable = inject("dbAvailable");

const BOOT_TIMEOUT_MS = 240_000;
const SIGNER_KID = "gogo-es256-2026-09-destination-tier";

const PaginatedPlacesSchema = paginatedSchema(PlaceSchema);

/**
 * Pins straight from the committed `reference-data/destinations.json`
 * snapshot (2026-08-19.0 release) — re-run `generate-destination-tier.ts`
 * and diff before changing any of these. Not guessed: every value here is
 * copied from the actual generated file.
 */
const TOKYO = {
  sourceId: "798895d4-5005-4b1d-b805-ee44a1f99a54",
  name: "Tokyo",
  lat: 35.676856994628906,
  lng: 139.76388549804688,
};
const ATHENS_GR = {
  sourceId: "adfbf49a-2781-4b77-8f02-b8ba400d50c6",
  name: "Athens",
  lat: 37.975563049316406,
  lng: 23.73482894897461,
};
const ATHENS_US = {
  sourceId: "3f0b8068-757c-4a76-9581-1c7201ff4254",
  name: "Athens",
  lat: 33.95976638793945,
  lng: -83.37641143798828,
};
const REYKJAVIK = {
  sourceId: "bc4247c1-deba-438e-bb36-788fec678333",
  name: "Reykjavik",
  lat: 64.14598083496094,
  lng: -21.94223976135254,
};
const ROME = { sourceId: "6fe9e7a3-65c4-4a9c-9aa2-3dddad62e1ab", name: "Rome" };
const OSLO = { sourceId: "2c1524a7-8d54-480e-b335-11a7d7918942", name: "Oslo" };
/** Netherlands — leading apostrophe (`'s-Hertogenbosch`). */
const APOSTROPHE_NAME = {
  sourceId: "b937075e-cb36-4d3e-a39e-97eac1dcba3f",
  name: "'s-Hertogenbosch",
};
/** Brazil — NFC diacritic, and the same name normalize.ts's own doc-comment
 * uses as its canonical example ("Belém" NFD vs NFC). */
const DIACRITIC_NAME = { sourceId: "bf9c8e9b-9b65-4044-9417-1d28f3dce674", name: "Belém" };
/** Iran — RTL script, embedded parentheses. */
const RTL_NAME = {
  sourceId: "300b9717-8013-46bf-a787-87be948fdd43",
  name: "(شهرک ابراهیم (شهید آیت الله ابراهیم رئیسی",
};
/** China — CJK, exactly 4 chars (clears PLACES_SEARCH_TEXT_ONLY_MIN_CHARS). */
const CJK_NAME = { sourceId: "8c239f23-c0e7-4ea0-8f11-f0f8317baf3e", name: "千泉街道" };
/**
 * Morocco — exactly 3 chars, a REAL seeded city (pop. 1,167,842), not a
 * synthetic probe. Round-1 review advisory A2: the floor test previously
 * used `q=Rio` (the city is actually "Rio de Janeiro", so the floor never
 * actually blocked its own name) — Fez has no longer form to fall back on,
 * so it demonstrates the floor's real cost. 54 seeded rows share this fate
 * (QUEUE-row draft, PR body: "destination search floor makes short city
 * names unreachable by their own exact name").
 */
const FEZ = {
  sourceId: "934d4327-381f-4abb-a53b-aecad75be1a1",
  name: "Fez",
};
/** B-7 follow-up (sub-floor exact-match arm) fixtures — all real seeded
 * 3-char tier rows sharing FEZ's fate (54 total; QUEUE-row draft). */
const VAN = { sourceId: "65ce9851-d747-4305-8666-4d49d8448784", name: "Van" };
const QOM = { sourceId: "b47c150c-ffcf-4d7f-9d53-4d30b346dc3e", name: "Qom" };
const UFA = { sourceId: "68cd8260-da3a-4080-86b6-3f2c287d8c21", name: "Ufa" };
/** China — 3-char CJK, the positive unicode-adversarial case (folding is a
 * no-op on CJK; still must round-trip through the exact-match arm). */
const HAILUN = { sourceId: "5fd34d6e-72cc-4735-8239-04486b2eb94a", name: "海伦镇" };
/**
 * Review R1 B2 (blocking): "accent-folded" — R-places-28's own headline
 * clause — had ZERO behavioral coverage; every prior fixture (FEZ, VAN,
 * QOM, UFA, HAILUN) is fold-invariant (its ASCII spelling never touches the
 * combining-mark strip). These 5 are real seeded 3-char tier rows whose
 * ASCII-folded spelling ONLY reaches them through `tierNameFoldExpr`'s
 * `normalize(…, NFD)` + combining-mark strip — verified against the
 * committed `reference-data/destinations.json` snapshot. `asciiQuery` is
 * the bare-ASCII spelling a user without an accented keyboard would type.
 */
const HUE = { sourceId: "9cc13945-6317-4904-acae-563b2121d783", name: "Huế", asciiQuery: "Hue" };
const MUS = { sourceId: "cbaeb270-1c03-4dd6-b641-ccdb9c1efb3f", name: "Muş", asciiQuery: "Mus" };
const NIS = { sourceId: "3f596f9a-bcf7-4160-bd53-8b8978d4b858", name: "Niš", asciiQuery: "Nis" };
const OME = { sourceId: "0bc521ce-ef5f-4404-b569-4bd84ae36439", name: "Ōme", asciiQuery: "Ome" };
const JAU = { sourceId: "6a18a8a3-2ea0-46f4-8d91-e6768a0e7f97", name: "Jaú", asciiQuery: "Jau" };
/**
 * Review R1 A3 (advisory): the exact arm's pagination/cursor semantics were
 * unpinned. Two real seeded rows both fold to "ota" (Ōta-ku, Tokyo's ward,
 * and a smaller Ōta — the seed's only sub-floor folded collision).
 */
const OTA_A = { sourceId: "21766799-1aab-4aea-8385-f5d6b96f79ba", name: "Ota" };
const OTA_B = { sourceId: "b85b1e2a-3fa5-4617-814c-aa0d82cbe1f9", name: "Ota" };

describe.skipIf(!dockerAvailable)("B-7 bootstrap destination tier (migrated seed)", () => {
  let suiteDb: SuiteDb;
  let db: PostgresJsDatabase<typeof schema>;
  let app: ReturnType<typeof createApp>;
  let signer: AccessTokenSigner;

  let seq = 0;
  const uniq = () => `${Date.now().toString(36)}${(seq++).toString(36)}`;

  beforeAll(async () => {
    suiteDb = await createSuiteDb("destination_tier");
    db = suiteDb.db;

    const signerPair = await generateKeyPair("ES256");
    signer = { privateKey: signerPair.privateKey, kid: SIGNER_KID };
    const authDeps: AuthRouterDeps = {
      db,
      verifier: {
        appleJwks: createLocalJWKSet({ keys: [] }),
        googleJwks: createLocalJWKSet({ keys: [] }),
        appleAudience: "com.gogo.travel",
        googleAudiences: ["gid.apps.example"],
      },
      signer,
      accessVerify: { publicKey: signerPair.publicKey },
      appleExchange: { exchange: () => Promise.reject(new Error("unused in this suite")) },
      appleCredentialsKey: Buffer.alloc(32, 7),
      logger: { warn: () => undefined },
    };
    app = createApp({
      auth: authDeps,
      // B-7 round-1 blocking finding: nothing previously exercised
      // search-hit -> POST /trips through this suite's app instance. `trips`
      // needs no ingest/rate-limit seam to prove the closure — `placesIngest`
      // stays absent (optional; a no-op skip, same posture as the places
      // deps' own stub below).
      trips: { db },
      places: {
        db,
        placesIngest: { enqueueDestination: () => undefined, enqueueSearchMiss: () => undefined },
        trackCoverageTask: (task) => {
          void task;
        },
      },
    });
  }, BOOT_TIMEOUT_MS);

  afterAll(async () => {
    await suiteDb?.drop();
  });

  async function seedUserWithToken() {
    const { user } = await createUserWithEntitlements(db, {
      email: `destination-tier-${uniq()}@example.com`,
      displayName: "Destination Tester",
      googleSub: `google-${uniq()}`,
    });
    const issued = await createSessionWithTokens(db, {
      userId: user.id,
      device: { platform: "ios" },
      signer,
    });
    return { userId: user.id, accessToken: issued.accessToken };
  }

  const request = (path: string, token?: string, init?: RequestInit) =>
    app.request(path, {
      ...init,
      headers: {
        ...(init?.body ? { "content-type": "application/json" } : {}),
        ...(token ? { authorization: `Bearer ${token}` } : {}),
        ...(init?.headers ?? {}),
      },
    });

  const search = (token: string | undefined, query: string) =>
    request(`/api/places/search?${query}`, token);

  async function searchOk(token: string, query: string) {
    const res = await search(token, query);
    expect(res.status).toBe(200);
    return PaginatedPlacesSchema.parse(await res.json());
  }

  // ===========================================================================
  // Row count pin (migration 0004)
  // ===========================================================================

  it("migration 0004 seeded exactly the pinned overture/locality row count", async () => {
    const [row] = await suiteDb.client<
      { n: string }[]
    >`select count(*) as n from places where source = 'overture' and category = 'locality'`;
    expect(Number(row?.n)).toBe(DESTINATION_TIER_ROW_COUNT);
  });

  // ===========================================================================
  // [B-7 repro] text-only destination search finds the bootstrap tier
  // ===========================================================================

  it("[B-7 repro] a text-only destination search (no bbox/near — the picker's exact request shape) finds Athens, Tokyo, and Reykjavik", async () => {
    const user = await seedUserWithToken();
    for (const city of [TOKYO, REYKJAVIK] as const) {
      const page = await searchOk(user.accessToken, `q=${encodeURIComponent(city.name)}`);
      expect(page.items.length).toBeGreaterThan(0);
      const hit = page.items.find((p) => p.source_id === city.sourceId);
      expect(hit, `${city.name} (${city.sourceId}) not found in results`).toBeDefined();
      expect(hit?.source).toBe("overture");
      expect(hit?.category).toBe("locality");
      expect(hit?.coarse_category).toBe("other"); // no `locality` rule (documented, README)
    }
    // Athens is ambiguous (GR capital + a US city) — both real tier rows,
    // both must surface (the duplicate-names case, verified below too).
    const athens = await searchOk(user.accessToken, "q=Athens");
    expect(athens.items.some((p) => p.source_id === ATHENS_GR.sourceId)).toBe(true);
    expect(athens.items.some((p) => p.source_id === ATHENS_US.sourceId)).toBe(true);
  });

  // ===========================================================================
  // [B-7 closure] search-hit -> POST /trips (the half B-7 repro alone never
  // proved) — B-7 round-1 blocking finding: no pin anywhere carried a tier
  // row from search into trip create. `POST /trips` has no `place_id`
  // param; the picker hands the searched-result fields straight through
  // (apps/mobile/src/data/trips-mutations.ts + apps/mobile/src/app/
  // (trips)/new.tsx:179-181 build `TripCreate` from `selectedPlace.{name,
  // lat,lng}` verbatim). This test sends exactly those fields.
  // ===========================================================================

  it("[B-7 closure] a search hit round-trips into a created trip — search -> pick -> POST /trips, the exact picker flow", async () => {
    const user = await seedUserWithToken();
    const page = await searchOk(user.accessToken, `q=${encodeURIComponent(ATHENS_GR.name)}`);
    const hit = page.items.find((p) => p.source_id === ATHENS_GR.sourceId);
    expect(hit, `${ATHENS_GR.name} (${ATHENS_GR.sourceId}) not found via search`).toBeDefined();

    const res = await request("/api/trips", user.accessToken, {
      method: "POST",
      body: JSON.stringify({
        name: "Greece Trip",
        // Exactly the fields trips-mutations.ts's TripCreate candidate
        // carries from a picked search result — no place_id exists.
        destination_name: hit?.name,
        destination_lat: hit?.lat,
        destination_lng: hit?.lng,
        start_date: "2026-10-01",
        end_date: "2026-10-10",
      }),
    });
    expect(res.status).toBe(201);
    const trip = TripWithRoleSchema.parse(await res.json());
    expect(trip.destination_name).toBe(ATHENS_GR.name);
    // The `toPlaceWire`/numeric round-trip (Number(row.lat)) survives into
    // trips.destination_lat/lng — the other half of the blocking finding.
    expect(trip.destination_lat).toBeCloseTo(ATHENS_GR.lat, 3);
    expect(trip.destination_lng).toBeCloseTo(ATHENS_GR.lng, 3);
  });

  it("4-char text-only query (the existing global floor, PLACES_SEARCH_TEXT_ONLY_MIN_CHARS) finds Rome and Oslo", async () => {
    const user = await seedUserWithToken();
    for (const city of [ROME, OSLO] as const) {
      expect(city.name.length).toBe(4);
      const page = await searchOk(user.accessToken, `q=${city.name}`);
      expect(page.items.some((p) => p.source_id === city.sourceId)).toBe(true);
    }
  });

  // ===========================================================================
  // [B-7 follow-up] sub-floor exact-match arm (Sean's ruling, 2026-09-14,
  // R-places-28): a text-only query shorter than
  // PLACES_SEARCH_TEXT_ONLY_MIN_CHARS no longer 400s — it runs an exact,
  // case-insensitive, accent-folded, trimmed match against the bootstrap
  // destination tier ONLY, never the trgm scan the floor still protects
  // against everywhere else.
  // ===========================================================================

  it("[B-7 follow-up] a 3-char exact-match query finds a real seeded city (Fez, MA, pop. 1.17M) — 200, not 400 (falsification: reverting routes.ts's arm branch, or `PlaceSearchQuerySchema`'s relaxed floor, turns this back into a 400)", async () => {
    const user = await seedUserWithToken();
    expect(FEZ.name.length).toBe(3);
    const res = await search(user.accessToken, `q=${FEZ.name}`); // 3 chars, no geo bound
    expect(res.status).toBe(200);
    const page = PaginatedPlacesSchema.parse(await res.json());
    expect(page.items.some((p) => p.source_id === FEZ.sourceId)).toBe(true);

    // Recovery (unaffected by this change — "Fez Morocco" is 11 chars, still
    // the trigram arm): padding past the floor still finds Fez.
    const recovered = await searchOk(user.accessToken, "q=Fez Morocco");
    expect(recovered.items.some((p) => p.source_id === FEZ.sourceId)).toBe(true);
  });

  it("[B-7 follow-up] case-insensitive: 'van' (lowercase) finds 'Van' (Turkey, pop. 468K)", async () => {
    const user = await seedUserWithToken();
    const page = await searchOk(user.accessToken, "q=van");
    expect(page.items.some((p) => p.source_id === VAN.sourceId)).toBe(true);
  });

  it("[B-7 follow-up] Qom and Ufa (both real 3-char seeded cities) are findable by exact name", async () => {
    const user = await seedUserWithToken();
    for (const city of [QOM, UFA] as const) {
      const page = await searchOk(user.accessToken, `q=${city.name}`);
      expect(page.items.some((p) => p.source_id === city.sourceId)).toBe(true);
    }
  });

  it("[B-7 follow-up] accent folding round-trips BOTH directions for 5 real seeded rows whose ASCII spelling is NOT fold-invariant (Huế, Muş, Niš, Ōme, Jaú) — the bare-ASCII spelling a user without an accented keyboard would type finds the accented row, and the accented spelling finds it too (review R1 B2, blocking: falsification — replacing tierNameFoldExpr's `normalize(…, NFD)` + combining-mark strip with a plain `lower(trim(x))` drops every one of the 5 ASCII-form queries to empty while all prior fixtures, being fold-invariant, stayed green)", async () => {
    const user = await seedUserWithToken();
    for (const city of [HUE, MUS, NIS, OME, JAU] as const) {
      expect(city.name.length).toBe(3);
      const asciiHit = await searchOk(user.accessToken, `q=${encodeURIComponent(city.asciiQuery)}`);
      expect(
        asciiHit.items.some((p) => p.source_id === city.sourceId),
        `q=${city.asciiQuery} should find ${city.name}`,
      ).toBe(true);

      const accentedHit = await searchOk(user.accessToken, `q=${encodeURIComponent(city.name)}`);
      expect(
        accentedHit.items.some((p) => p.source_id === city.sourceId),
        `q=${city.name} should find itself`,
      ).toBe(true);
    }
  });

  it("[B-7 follow-up] pagination over the exact arm's only folded collision ('Ota' — two real seeded rows) pages cleanly with limit=1, and a cursor MINTED BY THE TRIGRAM ARM resets to page 1 instead of erroring or skipping a row (review R1 A3, advisory: the exact arm's rank key is a constant 0::bigint, so `(0, id) < (foreignMicros, id)` holds for every row when foreignMicros is drawn from the trigram arm's much larger rank-key space — documented behavior, not a bug, since clients key cursors per query string)", async () => {
    const user = await seedUserWithToken();

    const full = await searchOk(user.accessToken, "q=Ota");
    expect(full.items.map((p) => p.source_id).sort()).toEqual(
      [OTA_A.sourceId, OTA_B.sourceId].sort(),
    );

    const page1 = await searchOk(user.accessToken, "q=Ota&limit=1");
    expect(page1.items).toHaveLength(1);
    expect(page1.nextCursor).not.toBeNull();

    const page2 = await searchOk(
      user.accessToken,
      `q=Ota&limit=1&cursor=${encodeURIComponent(page1.nextCursor as string)}`,
    );
    expect(page2.items).toHaveLength(1);
    expect(page2.nextCursor).toBeNull();
    expect(page2.items[0]?.id).not.toBe(page1.items[0]?.id);
    expect(new Set([page1.items[0]?.source_id, page2.items[0]?.source_id])).toEqual(
      new Set([OTA_A.sourceId, OTA_B.sourceId]),
    );

    // A cursor whose micros component sits in the TRIGRAM arm's rank-key
    // space (round-1 correctness A3's "~1e17" example) fed to the exact
    // arm: the exact arm's rank key is always 0, so (0, id) < (1e17, id)
    // holds regardless of id — the predicate excludes nothing and the
    // exact arm silently resets to page 1, rather than 500ing or skipping.
    const foreignCursor = encodeKeysetCursor({
      micros: "100000000000000000",
      id: "00000000-0000-0000-0000-000000000000",
    });
    const resetPage = await searchOk(
      user.accessToken,
      `q=Ota&limit=1&cursor=${encodeURIComponent(foreignCursor)}`,
    );
    expect(resetPage.items).toHaveLength(1);
    expect(resetPage.items[0]?.id).toBe(page1.items[0]?.id); // identical to page 1 — the reset
  });

  it("[B-7 follow-up] coarse_category IS applied on the exact arm (review R1 A1/ADVISORY-2, advisory: was silently dropped) — a category filter that doesn't match a locality's own coarse_category excludes it; a matching one keeps it", async () => {
    const user = await seedUserWithToken();
    // FEZ's own coarse_category is 'other' (no 'locality' coarse rule,
    // pinned above at the [B-7 repro] test) — a mismatched filter like
    // 'food' must exclude it, exactly like the trigram arm already does.
    const mismatched = await searchOk(user.accessToken, "q=Fez&coarse_category=food");
    expect(mismatched.items.some((p) => p.source_id === FEZ.sourceId)).toBe(false);

    const matched = await searchOk(user.accessToken, "q=Fez&coarse_category=other");
    expect(matched.items.some((p) => p.source_id === FEZ.sourceId)).toBe(true);
  });

  it("[B-7 follow-up] trailing/leading whitespace trims before the exact match ('Fez ' still finds Fez)", async () => {
    const user = await seedUserWithToken();
    const page = await searchOk(user.accessToken, `q=${encodeURIComponent(" Fez ")}`);
    expect(page.items.some((p) => p.source_id === FEZ.sourceId)).toBe(true);
  });

  it("[B-7 follow-up] a 3-char CJK query (folding is a no-op on non-Latin script) still round-trips exactly", async () => {
    const user = await seedUserWithToken();
    expect(HAILUN.name.length).toBe(3);
    const page = await searchOk(user.accessToken, `q=${encodeURIComponent(HAILUN.name)}`);
    expect(page.items.some((p) => p.source_id === HAILUN.sourceId)).toBe(true);
  });

  it("[B-7 follow-up] a 2-char query with NO exact tier match is 200 + empty, not 400 (the client shows 'no results' + offers custom-destination create, per apps/mobile/src/app/(trips)/new.tsx) — and this is the anti-prefix-widening mutation probe: 'Fe' must NOT prefix-match the real row 'Fez'", async () => {
    const user = await seedUserWithToken();
    const page = await searchOk(user.accessToken, "q=Fe");
    expect(page.items).toEqual([]);
    expect(page.items.some((p) => p.source_id === FEZ.sourceId)).toBe(false);
  });

  it("[B-7 follow-up] adversarial input never 500s and never loosens the exact match: SQL wildcard chars, an apostrophe, and a non-matching 3-char unicode string all resolve to 200 + empty", async () => {
    const user = await seedUserWithToken();
    for (const q of ["Fe%", "Fe_", "a'a", "Ⓕⓔⓩ"]) {
      const res = await search(user.accessToken, `q=${encodeURIComponent(q)}`);
      expect(res.status, `q=${q} should be 200`).toBe(200);
      const page = PaginatedPlacesSchema.parse(await res.json());
      expect(page.items, `q=${q} should match nothing`).toEqual([]);
    }
  });

  it("[B-7 follow-up] below the ABSOLUTE 2-char floor (1-char, all-spaces) is still 400 — unaffected by this change", async () => {
    const user = await seedUserWithToken();
    for (const q of ["V", "   "]) {
      const res = await search(user.accessToken, `q=${encodeURIComponent(q)}`);
      expect(res.status, `q=${JSON.stringify(q)} should be 400`).toBe(400);
      expect(((await res.json()) as ErrorEnvelope).error.code).toBe("VALIDATION_FAILED");
    }
  });

  it("[B-7 follow-up] a 4-char query ('Rome') still takes the TRIGRAM arm, not the exact-match arm — a superficially-similar 4-char query ('Fézz') does NOT spuriously match 'Fez' (EXPLAIN arm-selection pin)", async () => {
    const user = await seedUserWithToken();
    const rome = await searchOk(user.accessToken, "q=Rome");
    expect(rome.items.some((p) => p.source_id === ROME.sourceId)).toBe(true);

    const fezz = await searchOk(user.accessToken, "q=Fézz"); // "Fézz", 4 chars
    expect(fezz.items.some((p) => p.source_id === FEZ.sourceId)).toBe(false);

    // Direct EXPLAIN: the 4-char query drives the pg_trgm GIN (SARGABILITY
    // CONTRACT precedent, routes.db.test.ts) — NEVER the exact-match arm's
    // partial index — proving arm selection, not just result shape.
    const { sql: text, params: values } = placesSearchQuery(db, {
      userId: user.userId,
      q: "Rome",
      limit: 21,
    }).toSQL();
    const planRows = await suiteDb.client.begin(async (tx) => {
      await tx`set local enable_seqscan = off`;
      return tx.unsafe(`explain (costs false) ${text}`, values as never[]);
    });
    const plan = planRows.map((row) => String(Object.values(row as object)[0])).join("\n");
    expect(plan).toContain("places_name_trgm_idx");
    expect(plan).not.toContain("places_tier_name_folded_idx");
  });

  it("[B-7 follow-up] a sub-floor query drives the NEW partial index via an INDEX CONDITION, not a filter-only scan of it (EXPLAIN arm-selection pin; falsification: dropping `places_tier_name_folded_idx`, widening the predicate to `LIKE`, or DRIFTING the fold expression by one codepoint all change this plan — review R1 B1: the prior version of this pin only asserted the index NAME appeared, which a filter-only full-index scan also satisfies)", async () => {
    const { sql: text, params: values } = placesExactTierMatchQuery(db, {
      q: "Fez",
      limit: 21,
    }).toSQL();
    const planRows = await suiteDb.client.begin(async (tx) => {
      await tx`set local enable_seqscan = off`;
      return tx.unsafe(`explain (costs false) ${text}`, values as never[]);
    });
    const plan = planRows.map((row) => String(Object.values(row as object)[0])).join("\n");
    expect(plan).toContain("places_tier_name_folded_idx");
    // The load-bearing assertion: an INDEX COND (the fold expression itself
    // drives the index probe), never a Filter (which a plain full-index
    // scan — the drift scenario — would produce instead, at ~6,926 rows
    // removed for the same 6,927-row seed).
    expect(plan).toMatch(/Index Cond: \(lower\(regexp_replace/);
    expect(plan).not.toMatch(/Seq Scan on places\b/);
    expect(plan).not.toContain("places_name_trgm_idx");
  });

  it("[B-7 follow-up] Law #3: a stranger's custom place named exactly 'Fez' (even with category='locality', matching the tier predicate) is NEVER returned by the exact-match arm — and NEITHER is the CREATOR's own, because this arm is tier-rows-only, full stop (falsification: dropping the `source = 'overture'` predicate turns both red)", async () => {
    const creator = await seedUserWithToken();
    const stranger = await seedUserWithToken();

    const created = await request("/api/places", creator.accessToken, {
      method: "POST",
      body: JSON.stringify({ name: "Fez", category: "locality" }),
    });
    expect(created.status).toBe(201);
    const custom = PlaceSchema.parse(await created.json());

    const creatorView = await searchOk(creator.accessToken, "q=Fez");
    expect(creatorView.items.some((p) => p.id === custom.id)).toBe(false);
    expect(creatorView.items.some((p) => p.source_id === FEZ.sourceId)).toBe(true);

    const strangerView = await searchOk(stranger.accessToken, "q=Fez");
    expect(strangerView.items.some((p) => p.id === custom.id)).toBe(false);
    expect(strangerView.items.some((p) => p.source_id === FEZ.sourceId)).toBe(true);
  });

  // ===========================================================================
  // Ranking: custom place vs. tier row sharing a name (Law #3 posture)
  // ===========================================================================

  it("ranking: a same-named custom place and the tier row blend by proximity; the custom place stays creator-scoped", async () => {
    const creator = await seedUserWithToken();
    const stranger = await seedUserWithToken();

    // A custom place named exactly "Reykjavik", seeded much closer to the
    // near-anchor than the real tier row (64.146,-21.942) — same trigram
    // similarity to `q=reykjavik` (exact name match either way), so the
    // BLEND's proximity term is what decides the order (search-query.ts's
    // documented "similarity ties -> nearer wins" rule) — genuinely
    // untestable before this migration (there was no same-named spine row).
    const anchor = { lat: 64.1, lng: -21.9 }; // ~5.5km from the real tier row
    const customRes = await request("/api/places", creator.accessToken, {
      method: "POST",
      body: JSON.stringify({ name: "Reykjavik", lat: 64.101, lng: -21.901 }), // ~120m from anchor
    });
    expect(customRes.status).toBe(201);
    const custom = PlaceSchema.parse(await customRes.json());

    const blended = await searchOk(
      creator.accessToken,
      `q=reykjavik&near=${anchor.lat},${anchor.lng}&radius_m=50000`,
    );
    const ids = blended.items.map((p) => p.id);
    expect(ids).toContain(custom.id);
    const customIdx = ids.indexOf(custom.id);
    const tierIdx = blended.items.findIndex((p) => p.source_id === REYKJAVIK.sourceId);
    expect(tierIdx).toBeGreaterThanOrEqual(0);
    expect(customIdx).toBeLessThan(tierIdx); // nearer (custom) ranks first

    // Law #3: the stranger never sees the custom "Reykjavik" — only the
    // real tier row, even though names and query tie exactly.
    const strangerView = await searchOk(
      stranger.accessToken,
      `q=reykjavik&near=${anchor.lat},${anchor.lng}&radius_m=50000`,
    );
    expect(strangerView.items.some((p) => p.id === custom.id)).toBe(false);
    expect(strangerView.items.some((p) => p.source_id === REYKJAVIK.sourceId)).toBe(true);
  });

  // ===========================================================================
  // Duplicate names across countries (real data — no fixture needed)
  // ===========================================================================

  it("duplicate names across countries are both present and distinguishable by id/coordinates — but NOT by anything the API surfaces (QUEUE-row draft: 'destination picker cannot disambiguate same-named localities')", async () => {
    // Round-1 review advisory A1: this test used to assert distinguishability
    // via two direct db.select() calls — a property the user can never see.
    // Going through the real search endpoint documents what the picker
    // ACTUALLY returns: `PlaceSchema` (packages/shared/src/domains/place.ts)
    // has no region/country field, so "Cambridge" (452 tier rows share a
    // name across 208 distinct names) reads identically for every homonym.
    // Fixing that is a wire-contract change (Autonomy Contract trigger #1,
    // user-visible spec ambiguity) — out of scope here; parked as a QUEUE
    // row in the PR body, not silently improvised.
    const user = await seedUserWithToken();
    const athens = await searchOk(user.accessToken, "q=Athens");
    const gr = athens.items.find((p) => p.source_id === ATHENS_GR.sourceId);
    const us = athens.items.find((p) => p.source_id === ATHENS_US.sourceId);
    expect(gr, "Athens GR not found via /places/search").toBeDefined();
    expect(us, "Athens US not found via /places/search").toBeDefined();
    expect(gr?.name).toBe("Athens");
    expect(us?.name).toBe("Athens");
    // Every field the wire shape actually carries is identical except id
    // and coordinates — nothing the rendered list (`title=name`,
    // `subtitle=category`, apps/mobile/src/app/(trips)/new.tsx:307-308)
    // shows a user distinguishes them by.
    expect(gr?.category).toBe(us?.category);
    expect(gr?.coarse_category).toBe(us?.coarse_category);
    expect(gr?.id).not.toBe(us?.id);
    expect(gr?.lat).toBeCloseTo(ATHENS_GR.lat, 3);
    expect(us?.lat).toBeCloseTo(ATHENS_US.lat, 3);
    // 9,039.5 km apart (haversine, verified) — genuinely two different
    // places, not a dedup bug.
    expect(Math.abs((gr?.lat ?? 0) - (us?.lat ?? 0))).toBeGreaterThan(3);
  });

  // ===========================================================================
  // Adversarial names survive the SQL emitter (real rows, not synthesized)
  // ===========================================================================

  it("adversarial names (apostrophe, diacritic, RTL, CJK) round-trip byte-for-byte through the SQL emitter", async () => {
    for (const row of [APOSTROPHE_NAME, DIACRITIC_NAME, RTL_NAME, CJK_NAME]) {
      const [found] = await db
        .select()
        .from(schema.places)
        .where(eq(schema.places.sourceId, row.sourceId));
      expect(found, `${row.sourceId} missing`).toBeDefined();
      expect(found?.name).toBe(row.name);
    }
  });

  it("apostrophe, diacritic, and CJK names are ALSO findable via the search endpoint (storage AND search both survive)", async () => {
    const user = await seedUserWithToken();
    const hertogenbosch = await searchOk(user.accessToken, "q=Hertogenbosch");
    expect(hertogenbosch.items.some((p) => p.source_id === APOSTROPHE_NAME.sourceId)).toBe(true);

    const belem = await searchOk(user.accessToken, `q=${encodeURIComponent("belém")}`);
    expect(belem.items.some((p) => p.source_id === DIACRITIC_NAME.sourceId)).toBe(true);

    // Round-1 review advisory A6: CJK_NAME's own doc-comment says "clears
    // PLACES_SEARCH_TEXT_ONLY_MIN_CHARS" — a claim only search behavior
    // makes relevant — but it was previously only ever read back via
    // db.select(). Exercise it through the API too.
    const cjk = await searchOk(user.accessToken, `q=${encodeURIComponent(CJK_NAME.name)}`);
    expect(cjk.items.some((p) => p.source_id === CJK_NAME.sourceId)).toBe(true);
  });
});
